#include "Toolkit/AssetTypeGenerator/MaterialInstanceGenerator.h"

#include "MaterialDomain.h"
#include "Materials/MaterialExpressionStaticBoolParameter.h"
#include "Materials/MaterialExpressionStaticComponentMaskParameter.h"
#include "Materials/MaterialExpressionStaticSwitchParameter.h"
#include "Materials/MaterialInstanceConstant.h"
#include "Toolkit/ObjectHierarchySerializer.h"
#include "Toolkit/PropertySerializer.h"
#include "Toolkit/AssetDumping/AssetTypeSerializerMacros.h"
#include "Toolkit/AssetTypeGenerator/MaterialGenerator.h"

void UMaterialInstanceGenerator::PostInitializeAssetGenerator() {
	UPropertySerializer* Serializer = GetPropertySerializer();

	//transient data, generated by the editor automatically and can be different
	DISABLE_SERIALIZATION_RAW(UMaterialInstanceConstant, "TextureStreamingData");

	//not deserialized or compared directly, need special handling to make sure parameters in question exist
	DISABLE_SERIALIZATION_RAW(UMaterialInstanceConstant, "bHasStaticPermutationResource");

	//resolved by the editor by looking at parameter names and iterating material graph
	DISABLE_SERIALIZATION(FScalarParameterValue, ExpressionGUID);
	DISABLE_SERIALIZATION(FVectorParameterValue, ExpressionGUID);
	DISABLE_SERIALIZATION(FTextureParameterValue, ExpressionGUID);
	DISABLE_SERIALIZATION(FFontParameterValue, ExpressionGUID);
	DISABLE_SERIALIZATION(FRuntimeVirtualTextureParameterValue, ExpressionGUID);

	//deserialize manually to avoid cyclic dependencies
	DISABLE_SERIALIZATION_RAW(UMaterialInterface, "AssetUserData");
	this->AssetUserDataProperty = UMaterialInterface::StaticClass()->FindPropertyByName(TEXT("AssetUserData"));
}

UClass* UMaterialInstanceGenerator::GetAssetObjectClass() const {
	return UMaterialInstanceConstant::StaticClass();
}

FStaticParameterSet UMaterialInstanceGenerator::GetStaticParameterOverrides() const {
	const TSharedPtr<FJsonObject> AssetData = GetAssetData();
	const TSharedPtr<FJsonObject> AssetObjectProperties = AssetData->GetObjectField(TEXT("AssetObjectData"));
	const TSharedPtr<FJsonObject> StaticParametersObject = AssetObjectProperties->GetObjectField(TEXT("StaticParametersRuntime"));

	FStaticParameterSet StaticParameterOverrides;
	GetPropertySerializer()->DeserializeStruct(FStaticParameterSet::StaticStruct(), StaticParametersObject.ToSharedRef(), &StaticParameterOverrides);
	return StaticParameterOverrides;
}

void UMaterialInstanceGenerator::PopulateStageDependencies(TArray<FPackageDependency>& AssetDependencies) const {
	if (GetAssetData()->HasField(TEXT("SkipDependencies")) && GetAssetData()->GetBoolField(TEXT("SkipDependencies"))) return;
	if (GetCurrentStage() == EAssetGenerationStage::CONSTRUCTION) {
		const TSharedPtr<FJsonObject> AssetData = GetAssetData();
		const TSharedPtr<FJsonObject> AssetObjectProperties = AssetData->GetObjectField(TEXT("AssetObjectData"));

		const TArray<TSharedPtr<FJsonValue>> AssetUserDataObjects = AssetObjectProperties->GetArrayField(TEXT("AssetUserData"));
		const TArray<TSharedPtr<FJsonValue>> ReferencedObjects = AssetObjectProperties->GetArrayField(TEXT("$ReferencedObjects"));

		TArray<int32> AssetUserDataObjectIndices;
		for (const TSharedPtr<FJsonValue>& ObjectIndexValue : AssetUserDataObjects) {
			AssetUserDataObjectIndices.Add((int32) ObjectIndexValue->AsNumber());
		}
		
		TArray<FString> ReferencedPackages;
		for (const TSharedPtr<FJsonValue>& ObjectIndexValue : ReferencedObjects) {
			const int32 ObjectIndex = (int32) ObjectIndexValue->AsNumber();

			if (!AssetUserDataObjectIndices.Contains(ObjectIndex)) {
				GetObjectSerializer()->CollectObjectPackages(ObjectIndex, ReferencedPackages);
			}
		}

		for (const FString& DependencyPackageName : ReferencedPackages) {
			AssetDependencies.Add(FPackageDependency{*DependencyPackageName, EAssetGenerationStage::CDO_FINALIZATION});
		}
	}
	
	if (GetCurrentStage() == EAssetGenerationStage::PRE_FINSHED) {
		TArray<FString> ReferencedPackages;
		const TSharedPtr<FJsonObject> AssetData = GetAssetData();
		const TSharedPtr<FJsonObject> AssetObjectProperties = AssetData->GetObjectField(TEXT("AssetObjectData"));

		const TArray<TSharedPtr<FJsonValue>> AssetUserDataObjects = AssetObjectProperties->GetArrayField(TEXT("AssetUserData"));

		for (const TSharedPtr<FJsonValue>& AssetObjectValue : AssetUserDataObjects) {
			const int32 ObjectIndex = (int32) AssetObjectValue->AsNumber();
			GetObjectSerializer()->CollectObjectPackages(ObjectIndex, ReferencedPackages);
		}
		for (const FString& PackageName : ReferencedPackages) {
			AssetDependencies.Add(FPackageDependency{*PackageName, EAssetGenerationStage::CDO_FINALIZATION});	
		}
	}
}

void UMaterialInstanceGenerator::PreFinishAssetGeneration() {
	UMaterialInterface* Asset = GetAsset<UMaterialInterface>();
	const TSharedPtr<FJsonObject> AssetObjectProperties = GetAssetData()->GetObjectField(TEXT("AssetObjectData"));
	
	void* AssetUserData = AssetUserDataProperty->ContainerPtrToValuePtr<void>(Asset);
	const TSharedPtr<FJsonValue> AssetUserDataJson = AssetObjectProperties->GetField<EJson::Array>(TEXT("AssetUserData"));
	
	GetPropertySerializer()->DeserializePropertyValue(AssetUserDataProperty, AssetUserDataJson.ToSharedRef(), AssetUserData);
}

// Returns true when the parent material graph was modified (new parameter nodes were spawned).
// The caller is responsible for making sure the parent package is saved in that case.
bool EnsureStaticSwitchNodesPresent(UMaterial* Material, const FStaticParameterSet& StaticParameters) {
	TArray<FName> ExistingParameters;

	// Parameters that live inside material function calls are not visible as top level
	// expressions, so also collect them from the cached expression data. Real (non stub)
	// materials can keep their switches inside functions, and scanning only GetExpressions()
	// would spawn duplicate parameters into them. Generated stub materials update their
	// cached data right after their graph is built (UMaterialGenerator calls
	// UpdateCachedExpressionData), so this is reliable for both.
	{
		TArray<FMaterialParameterInfo> CachedParameterInfos;
		TArray<FGuid> CachedParameterGuids;
		Material->GetAllParameterInfoOfType(EMaterialParameterType::StaticSwitch, CachedParameterInfos, CachedParameterGuids);
		for (const FMaterialParameterInfo& ParameterInfo : CachedParameterInfos) {
			ExistingParameters.Add(ParameterInfo.Name);
		}
		CachedParameterInfos.Empty();
		CachedParameterGuids.Empty();
		Material->GetAllParameterInfoOfType(EMaterialParameterType::StaticComponentMask, CachedParameterInfos, CachedParameterGuids);
		for (const FMaterialParameterInfo& ParameterInfo : CachedParameterInfos) {
			ExistingParameters.Add(ParameterInfo.Name);
		}
	}

	for (UMaterialExpression* Expression : Material->GetExpressions()) {
		if (UMaterialExpressionStaticSwitchParameter* StaticSwitchParameter = Cast<UMaterialExpressionStaticSwitchParameter>(Expression)) {
			ExistingParameters.Add(StaticSwitchParameter->ParameterName);
		}
		if (UMaterialExpressionStaticBoolParameter* StaticBoolParameter = Cast<UMaterialExpressionStaticBoolParameter>(Expression)) {
			ExistingParameters.Add(StaticBoolParameter->ParameterName);
		}
		if (UMaterialExpressionStaticComponentMaskParameter* StaticMaskParameter = Cast<UMaterialExpressionStaticComponentMaskParameter>(Expression)) {
			ExistingParameters.Add(StaticMaskParameter->ParameterName);
		}
	}

	bool bMaterialGraphChanged = false;

	// This block was disabled for UE 5.2, which moved static switch parameters into
	// FStaticParameterSetEditorOnlyData and deprecated the old field. In UE 5.6 the switches
	// live in the runtime base again (FStaticParameterSetRuntimeData::StaticSwitchParameters;
	// the editor-only copy is now StaticSwitchParameters_DEPRECATED), so the original logic
	// works with the runtime field. Component masks are still editor-only data in 5.6.
	for (const FStaticSwitchParameter& StaticSwitchParameter : StaticParameters.StaticSwitchParameters) {
		if (!ExistingParameters.Contains(StaticSwitchParameter.ParameterInfo.Name)) {
			UMaterialExpressionStaticSwitchParameter* Parameter = UMaterialGenerator::SpawnMaterialExpression<UMaterialExpressionStaticSwitchParameter>(Material);
			Parameter->SetParameterName(StaticSwitchParameter.ParameterInfo.Name);
			bMaterialGraphChanged = true;
		}
	}

	for (const FStaticComponentMaskParameter& StaticComponentMaskParameter : StaticParameters.EditorOnly.StaticComponentMaskParameters) {
		if (!ExistingParameters.Contains(StaticComponentMaskParameter.ParameterInfo.Name)) {
			UMaterialExpressionStaticComponentMaskParameter* Parameter = UMaterialGenerator::SpawnMaterialExpression<UMaterialExpressionStaticComponentMaskParameter>(Material);
			Parameter->SetParameterName(StaticComponentMaskParameter.ParameterInfo.Name);
			bMaterialGraphChanged = true;
		}
	}

	if (bMaterialGraphChanged) {
		UMaterialGenerator::ConnectBasicParameterPinsIfPossible(Material, TEXT("Static Parameters Added from MaterialInstance"));
		UMaterialGenerator::ForceMaterialCompilation(Material);
	}
	return bMaterialGraphChanged;
}

// Compares the dumped static switch overrides against the ones stored in the generated asset.
// ExpressionGUID is deliberately ignored: the GUID in the dump belongs to the original game
// material, while generated stub parent materials re-create parameter expressions with fresh
// GUIDs and UMaterialInstance::PostLoad (UpdateParameterSet) rewrites the instance-side GUIDs
// to match the parent. Comparing GUIDs would flag such assets as "not up to date" on every run.
// Non-overridden entries are skipped because UpdateStaticPermutation trims them on apply.
static bool StaticSwitchParametersMatch(const TArray<FStaticSwitchParameter>& Overrides, const TArray<FStaticSwitchParameter>& Existing) {
	int32 NumOverridden = 0;
	for (const FStaticSwitchParameter& Override : Overrides) {
		if (!Override.bOverride) {
			continue;
		}
		NumOverridden++;

		const FStaticSwitchParameter* ExistingParameter = Existing.FindByPredicate([&](const FStaticSwitchParameter& Parameter) {
			return Parameter.ParameterInfo == Override.ParameterInfo;
		});
		if (ExistingParameter == NULL || !ExistingParameter->bOverride || ExistingParameter->Value != Override.Value) {
			return false;
		}
	}

	int32 NumExistingOverridden = 0;
	for (const FStaticSwitchParameter& Parameter : Existing) {
		if (Parameter.bOverride) {
			NumExistingOverridden++;
		}
	}
	return NumOverridden == NumExistingOverridden;
}

// Same as above for static component mask parameters (still editor-only data in UE 5.6).
static bool StaticComponentMaskParametersMatch(const TArray<FStaticComponentMaskParameter>& Overrides, const TArray<FStaticComponentMaskParameter>& Existing) {
	int32 NumOverridden = 0;
	for (const FStaticComponentMaskParameter& Override : Overrides) {
		if (!Override.bOverride) {
			continue;
		}
		NumOverridden++;

		const FStaticComponentMaskParameter* ExistingParameter = Existing.FindByPredicate([&](const FStaticComponentMaskParameter& Parameter) {
			return Parameter.ParameterInfo == Override.ParameterInfo;
		});
		if (ExistingParameter == NULL || !ExistingParameter->bOverride ||
			ExistingParameter->R != Override.R || ExistingParameter->G != Override.G ||
			ExistingParameter->B != Override.B || ExistingParameter->A != Override.A) {
			return false;
		}
	}

	int32 NumExistingOverridden = 0;
	for (const FStaticComponentMaskParameter& Parameter : Existing) {
		if (Parameter.bOverride) {
			NumExistingOverridden++;
		}
	}
	return NumOverridden == NumExistingOverridden;
}

void UMaterialInstanceGenerator::PopulateSimpleAssetWithData(UObject* Asset) {
	Super::PopulateSimpleAssetWithData(Asset);
	UMaterialInstanceConstant* MaterialInstance = CastChecked<UMaterialInstanceConstant>(Asset);

	if (!MaterialInstance->Parent) {
		UE_LOG(LogAssetGenerator, Error, TEXT("Failed to deserialize Parent Material for MaterialInstance %s. Falling back to default material"), *MaterialInstance->GetPathName());
		MaterialInstance->Parent = UMaterial::GetDefaultMaterial(EMaterialDomain::MD_Surface);
		return;
	}

	UMaterial* ParentMaterial = MaterialInstance->GetMaterial();
	const FStaticParameterSet StaticParameterOverrides = GetStaticParameterOverrides();

	// If we had to spawn missing parameter nodes into the (stub) parent material, remember its
	// package so it is saved together with this asset. The parent asset was already saved during
	// its own generation pass, so without this the spawned nodes would be silently lost.
	if (EnsureStaticSwitchNodesPresent(ParentMaterial, StaticParameterOverrides)) {
		ModifiedParentPackages.AddUnique(ParentMaterial->GetOutermost());
	}
	MaterialInstance->UpdateStaticPermutation(StaticParameterOverrides);
	
	//Regenerate ExpressionGUID values on updated parameter values by calling UpdateParameters()
	//but since it's protected we're calling post load instead, even though it does a little bit more than that, but who cares
	MaterialInstance->PostLoad();
}

bool UMaterialInstanceGenerator::IsSimpleAssetUpToDate(UObject* Asset) const {
	UMaterialInstanceConstant* MaterialInstance = CastChecked<UMaterialInstanceConstant>(Asset);
	const TSharedPtr<FJsonObject> AssetObjectProperties = GetAssetData()->GetObjectField(TEXT("AssetObjectData"));
	
	if (!Super::IsSimpleAssetUpToDate(Asset)) {
		return false;
	}
	
	const void* AssetUserData = AssetUserDataProperty->ContainerPtrToValuePtr<void>(Asset);
	const TSharedPtr<FJsonValue> AssetUserDataJson = AssetObjectProperties->GetField<EJson::Array>(TEXT("AssetUserData"));

	if (!GetPropertySerializer()->ComparePropertyValues(AssetUserDataProperty, AssetUserDataJson.ToSharedRef(), AssetUserData)) {
		return false;
	}

	const FStaticParameterSet StaticParameterOverrides = GetStaticParameterOverrides();
	const FStaticParameterSet ExistingStaticParameters = MaterialInstance->GetStaticParameters();

	// In UE 5.6 static switches are runtime data again (see EnsureStaticSwitchNodesPresent),
	// so the comparison disabled for UE 5.2 can be performed. GUIDs are ignored on purpose
	// (see StaticSwitchParametersMatch).
	return StaticSwitchParametersMatch(StaticParameterOverrides.StaticSwitchParameters, ExistingStaticParameters.StaticSwitchParameters) &&
		StaticComponentMaskParametersMatch(StaticParameterOverrides.EditorOnly.StaticComponentMaskParameters, ExistingStaticParameters.EditorOnly.StaticComponentMaskParameters);
}

void UMaterialInstanceGenerator::GetAdditionalPackagesToSave(TArray<UPackage*>& OutPackages) {
	OutPackages.Append(ModifiedParentPackages);
}

FTopLevelAssetPath UMaterialInstanceGenerator::GetAssetClass() {
	return FTopLevelAssetPath(UMaterialInstanceConstant::StaticClass());
}
